### ISSUE TITLE
Bug: new bin version is published on target deletion instead of grouping changes

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-worker#152]
### What happened?

While testing (locally) the remove targets feature I had a situation where two targets ended up in the same bin. Here is the content of `bins-1.json` version 2 (where I have highlighted the targets: 
<img width="567" alt="image" src="https://user-images.githubusercontent.com/16246778/209212449-0b688c8a-6787-4383-b2cd-f8343a459789.png">

Then, I made a REST API call to the `DELETE /api/v1/targets/` endpoint deleting both `a/b/file3.tar.gz` and `a/file2.tar.gz` target files and I noticed that a new version 3 of `bins-1.json` was out and it contained the following: 
<img width="553" alt="image" src="https://user-images.githubusercontent.com/16246778/209212863-60aebd6d-5b74-484a-8ae9-deab6b91ad9f.png">

as you can see only one of the targets was removed - `a/file2.tar.gz`.
Then a fourth version was published of `bins-1.json` and this time it had all of the targets removed: 
<img width="552" alt="image" src="https://user-images.githubusercontent.com/16246778/209213555-942a716d-059b-4ebd-8013-eff8dbe300e0.png">

### What behavior did you expect?

After my REST API call to the `DELETE /api/v1/targets/` endpoint I expected only one new version of `bins-1.json` to be published.
The way it works now makes it's like I didn't make one API call with multiple files for deletion, but instead it's like I made multiple API calls.
This could slow the work of RSTUF a lot if it's is deployed on a system with lots of targets.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
I think this bug is solved by https://github.com/vmware/repository-service-tuf-worker/pull/145
- https://github.com/vmware/repository-service-tuf-worker/pull/145

**Comment by MVrachev** [comment]
I thought so, but I wanted to document it, so we can verify it after we merge https://github.com/vmware/repository-service-tuf-worker/pull/145

**Comment by MVrachev** [comment]
I confirm that this bug doesn't appear anymore.
What I did to reproduce it is:
1. deployed RSTUF Worker container based on the latest main and RSTUF API
2. completed the bootstrap ceremony
3. added the two targets: `a/b/file3.tar.gz` and `a/file2.tar.gz` which ended up in `2.bins-0.json`.
4. then deleted both of them with one API call to `DELETE /api/v1/targets/`
5. verified that `3.bins-0.json` didn't have any of the targets and `4.bins-0.json` was not published

I am closing the issue.
