### ISSUE TITLE
Enhancement: Add unit tests for local.py for LocalKeyVault

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-worker#253]
### What do you want to share with us?

I can see we have some parts that are not covered for UT in LocalKeyVault (`local.py`)
See https://app.codecov.io/gh/vmware/repository-service-tuf-worker/blob/main/repository_service_tuf_worker/services/keyvault/local.py for more information.

To follow the coverage locally while you are implementing, use the `make coverage` to generate the HTML coverage file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fsavoia** [comment]
I can take this task.

**Comment by kairoaraujo** [comment]
I implemented some UT for the PR [Improve the SQL worker container configuration](https://github.com/repository-service-tuf/repository-service-tuf-worker/issues/253#top) which can be a good reference for this issue.

**Comment by kairoaraujo** [comment]
I'm sorry, @fsavoia. But I proposed some changes to the LocalKeyVault (`services/keyvault/local.py`), which refactored the code, and I added the UT.
I can still help you find an issue if you want to contribute. 😄
