### ISSUE TITLE
Task: add task "update_settings" in Repository

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-worker#297]
### What is the task about?

This endpoint is suggested in the RSTUF API issue: https://github.com/repository-service-tuf/repository-service-tuf-api/issues/350
We want to add support for it.

### Parent feature

- https://github.com/repository-service-tuf/repository-service-tuf/issues/347

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
During a call with @kairoaraujo, we decided it's better to split this feature into three parts:
1. one API endpoint that will update the config settings (this API)
2. one API endpoint to enforce bump of the online roles
3. a flag for this endpoint (PUT config) to enforce bump online roles

**Comment by kairoaraujo** [comment]
We can file later in the umbrella the new issues/features (1) and (2) once they will require new interactions on API and Worker.
