### ISSUE TITLE
Task: Implement Metadata Update Distributed Async Signature feature

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-worker#336]
### What is the task about?

This task is about the Worker running tasks for Signing a TUF metadata.

It requires:
- #300, which implements the base `sign_metadata`

Required changes:

* Metadata Update
  - It does need to check the signing state (threshold) like in Bootstrap and update TUF Settings (Redis `<ROLENAME>_SIGNING`) and persist the metadata.
  - It is important to validate the signatures threshold of the previous and new metadata to have consistency. [Specification reference.](https://theupdateframework.github.io/specification/latest/#key-management-and-migration)
  
**Note:** RSTUF currently has only one Role with offline key(s), but this process might be helpful in the future to support other offline roles or even support delegate roles using offline keys.

### Parent feature

- https://github.com/repository-service-tuf/repository-service-tuf/issues/327

### References

- #300
- https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/313#discussion_r1269408892

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
We should be able to close this issue, right @lukpueh and @kairoaraujo?
