### ISSUE TITLE
Task: Implement Key Vault for AWS KMS

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-worker#344]
### What is the task about?

This task is about implementing a new RSTUF [Key Vault Service](https://github.com/repository-service-tuf/repository-service-tuf-worker/blob/f86f6a8ba9fd0d9a2aff4376e8ffdbc50010ece0/repository_service_tuf_worker/interfaces.py#L24) which supports AWS KMS.

This functionality enables the RSTUF users to use the online key from AWS KMS.
The Security Systems Lib creates a [`Signer`](https://github.com/secure-systems-lab/securesystemslib/blob/main/securesystemslib/signer/_aws_signer.py) which supports AWS KMS.

For this task we can introduce to the RSTUF Development [KMS localstack](https://docs.localstack.cloud/user-guide/aws/kms/) for development and tests

### Parent feature

- https://github.com/repository-service-tuf/repository-service-tuf/issues/24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
For this issue to be fixed it's better we wait for a new version of securesystemslib which will include the new AWSSigner they have introduced post their 0.28.0 release.

**Comment by lukpueh** [comment]
Is there anything missing after having merged #452?

**Comment by MVrachev** [comment]
I don't think there is.
Let's close it. If there is a need for a similar issue we can always restore it or create a new one.
