### ISSUE TITLE
Task: Replace mock `datetime` by `fake_datetime` fixture

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-worker#352]
### What is the task about?

We recently implemented a new fixture that automatically mocks the datetime. 

This task is about replacing the monkeypatch mock by the fixture

Remove mocks like this

https://github.com/repository-service-tuf/repository-service-tuf-worker/blob/2e071289e5353d5f47001e35942f477f82f4074f/tests/unit/tuf_repository_service_worker/test_repository.py#L233-L239

By a the fixture `mocked_datetime` which does all 5 lines 😀

https://github.com/repository-service-tuf/repository-service-tuf-worker/blob/2e071289e5353d5f47001e35942f477f82f4074f/tests/unit/tuf_repository_service_worker/test_repository.py#L770-L771

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fsavoia** [comment]
Can you assign this issue to me?

**Comment by MVrachev** [comment]
Done.
