### ISSUE TITLE
Add support for AWS S3

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-worker#49]
Implement Metadata Storage support for S3

**Comment by MVrachev** [comment]
The core implementation adding support for AWS S3 is in this pr #360.

In a conversation with @kairoaraujo he mentioned that additionally he wants to:

- [ ] prepare functional GitHub actions for tests for AWS S3
- [ ] create a python-TUF ngclient fetcher for AWS S3

**Comment by MVrachev** [comment]
This one is closed with pr https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/360.
