### ISSUE TITLE
Bug: save Timestamp and Root together during metadata update

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-worker#494]
### What happened?

The root persistency in the storage should be done together with the timestamp during the Metadata Update.
This was identified during the investigation of another bug:
 - https://github.com/repository-service-tuf/repository-service-tuf-worker/issues/491

Due to storage latency, saving two files together is almost impossible using file storage (S3, file system, etc.)

We should create a simple check during the saving and the client needs to handle the failure/retry.

https://github.com/repository-service-tuf/repository-service-tuf-worker/blob/70f548f951850f84a4e0677ad87483494533b65f/repository_service_tuf_worker/repository.py#L1304-L1311

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
As I said in this comment https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/501#issuecomment-2084816695 I think we solved this issue.
I created another issue to review how we recover from a situation when root update/persistence fails: #512.

We can close this issue.
